export default {
    leadGroupIndex: [
        { nameEN: "No.", nameTH: "", class: "", action: "", sort: false },
        { nameEN: "Group", nameTH: "", class: "text-start", action: "", sort: false },
        { nameEN: "Date", nameTH: "", class: "", action: "", sort: false },
        { nameEN: "State", nameTH: "", class: "", action: "", sort: false },
        { nameEN: "Perdictive Dialing", nameTH: "", class: "", action: "", sort: false },
        { nameEN: "Created By", nameTH: "", class: "text-start", action: "", sort: false },
        { nameEN: "Action", nameTH: "", class: "", action: "", sort: false },
    ],
    leadGroupCreate: [
        { nameEN: "No.", nameTH: "",  class: "", action: "", sort: false },
        { nameEN: "unique ID", nameTH: "", class: "", action: "", sort: false },
        { nameEN: "First name", nameTH: "", class: "text-start", action: "", sort: false },
        { nameEN: "Last name", nameTH: "", class: "text-start", action: "", sort: false },
        { nameEN: "Phone", nameTH: "", class: "text-start", action: "", sort: false },
        { nameEN: "Email", nameTH: "", class: "text-start", action: "", sort: false },
        { nameEN: "Total Amount Due", nameTH: "", class: "text-start", action: "", sort: false },
        { nameEN: "Status", nameTH: "", class: "", action: "", sort: false },
    ],
    leadGroupEdit: [
        { nameEN: "No.", nameTH: "",  class: "", action: "", sort: false },
        { nameEN: "unique ID", nameTH: "", class: "", action: "", sort: false },
        { nameEN: "First name", nameTH: "", class: "text-start", action: "", sort: false },
        { nameEN: "Last name", nameTH: "", class: "text-start", action: "", sort: false },
        { nameEN: "Phone", nameTH: "", class: "text-start", action: "", sort: false },
        { nameEN: "Email", nameTH: "", class: "text-start", action: "", sort: false },
        { nameEN: "Total Amount Due", nameTH: "", class: "text-start", action: "", sort: false },
        { nameEN: "Status", nameTH: "", class: "", action: "", sort: false },
    ],
    leadGroupView: [
        { nameEN: "No.", nameTH: "", class: "", action: "", sort: false },
        { nameEN: "unique ID", nameTH: "", class: "", action: "", sort: false },
        { nameEN: "Lead Name", nameTH: "", class: "text-start", action: "", sort: false },
        { nameEN: "Phone", nameTH: "", class: "text-start", action: "", sort: false },
        { nameEN: "Email", nameTH: "", class: "text-start", action: "", sort: false },
        { nameEN: "Total Amount Due", nameTH: "", class: "", action: "", sort: false },
        { nameEN: "Contact Date (latest)", nameTH: "text-start", class: "", action: "", sort: false },
        { nameEN: "Contact Status", nameTH: "", class: "", action: "", sort: false },
        { nameEN: "Ticket Status", nameTH: "", class: "", action: "", sort: false },
        { nameEN: "Assign To", nameTH: "", class: "text-start", action: "", sort: false },
        { nameEN: "Action", nameTH: "", class: "", action: "", sort: false },
    ],
}